### ISSUE TITLE
x11-themes/arc-theme::jorgicio causing strange problems with portage

### ISSUE THREAD

**Issue by redblade7** [jorgicio/jorgicio-gentoo-overlay#191]
x11-themes/arc-theme::jorgicio is causing strange problems with portage.

See here:

https://forums.gentoo.org/viewtopic-p-8386448.html

**Comment by jorgicio** [comment]
Hi, I just noted this and I think what could be the problem.

Recently, Inkscape fails at build if USE="imagemagick" is enabled because it requires an older version of Imagemagick (6.9.x). The problem here is with that dependency, so it may fail with any package with depends on Inkscape. See [this bug](https://bugs.gentoo.org/663468) for more information.

Also, try to build Inkscape without the USE-flag="imagemagick" because, as I looked in the forum, it's at dependency time.

**Comment by jorgicio** [comment]
Ok, the pre-rendered USE-flag came back, so arc-theme can be installed properly. Resync and try again with arc-theme. Just tried and now it works.

The inkscape issue is unrelated here now, so I'll close this.
