### ISSUE TITLE
media/xawtv-3.106 not compiling in gentoo

### ISSUE THREAD

**Issue by russelld58** [jorgicio/jorgicio-gentoo-overlay#195]
This is failing to build and was eventually successful with use flag for media-tv/xawtv
in /etc/portage/package.use 

    media-tv/xawtv   -cpu_flags_x86_mmx

this post was most helpful:
https://github.com/jorgicio/jorgicio-gentoo-overlay/issues/82

this is on a i7 HP laptop with intel mobo and onboard graphics.
"emerge --info" is here:
[https://gist.github.com/russelld58/0d7e0ffe212832bfa71de9d1bfc28b72](https://gist.github.com/russelld58/0d7e0ffe212832bfa71de9d1bfc28b72)

Maybe have a test to see if  "cpu_flags_x86_mmx" needed?
Or remove the flag "cpu_flags_x86_mmx" from the the ebuild?
Would have sped things up considerably! though learned some stuff in meantime ;-)

**Comment by jorgicio** [comment]
Hi. The issue with that use-flag enabled comes from some time ago and I tried to research about why it fails when compiling with mmx and I couldn't find an answer. I had that issue too, no matter the output of the emerge --info command. That's why I tried to keep that USE-flag masked and you should disable it in the meantime, but for some strange reason, despite being masked in the package.use.mask file (see it in the "profiles" folder), it keeps asking for that.

Sorry for the inconveniences.

**Comment by russelld58** [comment]
Hi Jorgicio,
I would have been completely lost without the valuable help from the previous post on the same error!
After I applied it, the package emerged and which then allowed prey to emerge.

When you have a moment, please add a README.md for media-tv/xawtv outlining this issue and the solution.  This would be great assistance to us in user-land!  ;-)

Your effort toward maintaining your overlay is very much appreciated!

**Comment by jorgicio** [comment]
Fine. I'll write that comment about that as a workaround.

Thanks!
